name: SmpCore
version: '1.1-SNAPSHOT'
main: me.creonc.smpcore.SmpCore
api-version: '1.20'

commands:
  selectclass:
    usage: "/selectclass <Class name>"
    description: "todo"
    aliases: [class]
