name: SmpCore
version: '1.1-SNAPSHOT'
main: me.creonc.smpcore.SmpCore
api-version: '1.20'

commands:
  selectclass:
    description: Select a class.
    usage: /selectclass <class>
  selectclassconfirm:
    description: Confirm the selected class.
    usage: /selectclass confirm
  selectclasscancel:
    description: Cancel the selected class.
    usage: /selectclass cancel