name: SmpCore
version: '0.1.4'
main: me.creonc.smpcore.SmpCore
api-version: '1.20'
author: CreonC

commands:
  selectclass:
    description: Select a class.
    usage: /selectclass <class>
  selectclassconfirm:
    description: Confirm the selected class.
    usage: /selectclass confirm
  selectclasscancel:
    description: Cancel the selected class.
    usage: /selectclass cancel
  selectclassunselect:
    description: Unselect the current class.
    usage: /selectclass unselect